version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true
    environment:
      BINTRAY_REPO: custom
      PACKAGE_VCS_URL: https://github.com/aursu/rpmbuild-util-linux
    steps:
      - run:
          name: Upgrade Docker CE
          command: |
            sudo apt-get update
            sudo apt-get install docker-ce=18.03.1~ce-0~ubuntu
      - run:
          name: Upgrade Docker Compose
          command: |
            sudo curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
      - checkout
      - run:
          name: Git submodules sync
          command: |
            git submodule sync
            git submodule update --init
      - run:
          name: Pull images for RPM build docker services
          command: |
            docker-compose -f rpmbuild/docker-compose.yml pull
            docker-compose -f rpmbuild/docker-compose.bintray.yml pull
      - run:
          name: Start docker services for rpmbuild
          command: docker-compose -f rpmbuild/docker-compose.yml up -d
          background: true
          no_output_timeout: 2h
      - run:
          name: Build Docker images
          command: |
            docker-compose -f docker-compose.base.yml build
            docker-compose build --no-cache
      - run:
          name: Build RPM packages
          command: docker-compose up
      - run:
          name: Upload RPM packages into Bintray
          command: |
            docker-compose -f rpmbuild/docker-compose.bintray.yml run --rm \
              -e BINTRAY_USER=$BINTRAY_USER \
              -e BINTRAY_API_KEY=$BINTRAY_API_KEY \
              -e BINTRAY_REPO=$BINTRAY_REPO \
              -e PACKAGE_VCS_URL=$PACKAGE_VCS_URL centos7bintray
